### ISSUE TITLE
What's the benefit of using this as opposed to stripe.js?

### ISSUE THREAD

**Issue by Tyler-Darby** [zyramedia/cordova-plugin-stripe#3]
Is there any reason to use the native SDK as opposed to the JS SDK? 

Additionally, is this stable enough to be used in production or should I stick to the JS SDK For now?

**Comment by ihadeed** [comment]
Stripe blocked my app from using `stripe.js` because it wasn't executed on a HTTPS host. Which is why I created this plugin. It solved that problem for me since it uses Stripe's native SDKs.

The plugin is stable enough to be used in production. But it only provides functionality to create a credit card token. It doesn't implement other native SDK features such as Apple Pay or Android Wallet support.

**Comment by mdipierro** [comment]
Perfect thanks again. That is all I need to know. :-)
