### ISSUE TITLE
not really an issue just a question ... but not sure where to ask

### ISSUE THREAD

**Issue by mdipierro** [zyramedia/cordova-plugin-stripe#6]
First of all thanks for the plugin. Question is: is this plugin just a convenience or is it necessary? Can one just stripe.js to get the token?

**Comment by ihadeed** [comment]
@mdipierro read my answer here: https://github.com/zyramedia/cordova-plugin-stripe/issues/3#issuecomment-277621322

**Comment by ihadeed** [comment]
Update: I just tried to reproduce the issue I was having initially and I failed. Not sure how I got that error message in the first place.

But anyways, I personally would rather use their native SDK because it will ensure that my stripe functionality works a 100%. Imagine a scenario where the user launches your app while they're offline, the app will try to load Stripe.js from `https://js.stripe.com/v2/` and fail. Then when your app tries to call the global variable `Stripe`, it will return undefined and will probably cause your app to not function properly.
