### ISSUE TITLE
no suitable constructor found for Stripe(no arguments)

### ISSUE THREAD

**Issue by Deadsoil** [zyramedia/cordova-plugin-stripe#8]
I just started getting this error randomly when trying to build my project. Any ideas? never had the issue before.

platforms/android/src/com/zyramedia/cordova/stripe/CordovaStripe.java:24: error: no suitable constructor found for Stripe(no arguments)
        stripeObject = new Stripe()

    constructor Stripe.Stripe(Context) is not applicable
      (actual and formal argument lists differ in length)
    constructor Stripe.Stripe(Context,String) is not applicable
      (actual and formal argument lists differ in length)

**Comment by ihadeed** [comment]
You're getting this error because Stripe updated their SDK, I will need to modify the code here to work with their latest SDK.

For now, I committed a quick hot fix to get your app working: https://github.com/zyramedia/cordova-plugin-stripe/commit/bb2d248e64ccc5062f38c4f3786b89481976c828

Just uninstall the plugin and re-install it from the repository URL instead. I will keep this issue open and let you know once the issue is fully resolved.

**Comment by brianlittmann** [comment]
You can also just update the `.gradle` file in `platforms/android/cordova-plugin-stripe/` if you're wanting to get up and running locally.

**Comment by Deadsoil** [comment]
That's what I ended up doing. Cheers guys
